# Generated by Django 5.2.17 on 2026-09-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turbine",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("location_reference", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArchivedRun",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("issued_at", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("weather_model", models.CharField(max_length=160)),
                ("source_url", models.URLField(max_length=1000)),
                ("records", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turbine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weather_archive.turbine",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("as_of", models.DateTimeField()),
                ("start_time", models.DateTimeField()),
                ("provider", models.CharField(max_length=60)),
                ("weather_model", models.CharField(max_length=160)),
                ("provenance", models.JSONField()),
                ("records", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turbine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weather_archive.turbine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["turbine", "as_of", "start_time"],
                        name="weather_arc_turbine_e1be3b_idx",
                    )
                ],
            },
        ),
    ]
