# Generated by Django 5.2.17 on 2026-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_archive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedrun",
            name="schema_version",
            field=models.CharField(default="legacy", max_length=40),
        ),
    ]
