# Generated by Django 5.2.17 on 2026-09-23 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("weather_archive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("as_of", models.DateTimeField()),
                ("start_time", models.DateTimeField()),
                ("status", models.CharField(default="running", max_length=20)),
                ("model_version", models.CharField(blank=True, max_length=160)),
                ("is_demo", models.BooleanField(default=False)),
                ("records", models.JSONField(default=list)),
                ("trace", models.JSONField(default=list)),
                ("analysis", models.JSONField(default=dict)),
                ("error", models.JSONField(default=dict)),
                ("request_params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weather_archive.weathersnapshot",
                    ),
                ),
                (
                    "turbine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weather_archive.turbine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
