# Generated by Django 5.2.17 on 2026-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="alignment_confirmed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="response_schema_version",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
